apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: eulard-frontend-config
  namespace: eulard
  labels:
    app.kubernetes.io/part-of: eulard
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
