apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eulard-web-hpa
  namespace: eulard
  labels:
    app.kubernetes.io/part-of: eulard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eulard-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
