#!/usr/bin/env bash
# =============================================================================
# Populate auto-generated secrets in GCP Secret Manager
# Usage: ./scripts/populate-secrets.sh [environment]
# =============================================================================
set -euo pipefail

ENV="${1:-dev}"
PROJECT="kelihi-ai-platform"

echo "==> Populating auto-generated secrets for eulard (${ENV})"

# NEXTAUTH_SECRET — session cookie signing
if ! gcloud secrets versions list "eulard-nextauth-secret-${ENV}" \
    --project="${PROJECT}" --format='value(name)' 2>/dev/null | head -1 | grep -q .; then
  echo "    Generating NEXTAUTH_SECRET..."
  openssl rand -base64 32 | tr -d '\n' | \
    gcloud secrets versions add "eulard-nextauth-secret-${ENV}" \
      --project="${PROJECT}" --data-file=-
else
  echo "    NEXTAUTH_SECRET already exists, skipping"
fi

# DB_PASSWORD is auto-generated by Terraform — skip

# Manual secrets (remind the operator)
echo ""
echo "==> Manual secrets (set these yourself if not already done):"
echo "    gcloud secrets versions add eulard-google-oauth-client-id-${ENV} --project=${PROJECT} --data-file=-"
echo "    gcloud secrets versions add eulard-google-oauth-client-secret-${ENV} --project=${PROJECT} --data-file=-"
echo "    gcloud secrets versions add eulard-anthropic-api-key-${ENV} --project=${PROJECT} --data-file=-"
echo ""
echo "==> Done."
