#!/usr/bin/env bash
# =============================================================================
# Pull secrets from GCP Secret Manager into .env.local
#
# Fetches dev secrets from the kelihi-ai-platform project and writes them
# to .env.local for local development. Requires gcloud CLI authenticated.
#
# Usage: ./scripts/pull-secrets.sh [environment]
#   environment: dev (default) | prod
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"
ENV="${1:-dev}"
PROJECT="kelihi-ai-platform"
ENV_FILE="${ROOT_DIR}/.env.local"

echo "==> Pulling secrets from GCP Secret Manager (${ENV}) → .env.local"
echo ""

# Ensure gcloud is authenticated
if ! gcloud auth print-identity-token &>/dev/null; then
  echo "ERROR: gcloud not authenticated. Run:"
  echo "  gcloud auth login"
  exit 1
fi

fetch_secret() {
  local name="$1"
  local value
  value=$(gcloud secrets versions access latest \
    --secret="${name}-${ENV}" \
    --project="${PROJECT}" 2>/dev/null) || true
  if [ -z "${value}" ]; then
    echo "  WARNING: ${name}-${ENV} not found or empty"
  else
    echo "  OK: ${name}-${ENV}"
  fi
  echo "${value}"
}

NEXTAUTH_SECRET=$(fetch_secret "eulard-nextauth-secret")
DB_PASSWORD=$(fetch_secret "eulard-db-password")
AUTH_GOOGLE_CLIENT_ID=$(fetch_secret "eulard-google-oauth-client-id")
AUTH_GOOGLE_CLIENT_SECRET=$(fetch_secret "eulard-google-oauth-client-secret")
ANTHROPIC_API_KEY=$(fetch_secret "eulard-anthropic-api-key")

echo ""

# Write .env.local — uses local postgres defaults for DB_HOST/DB_PORT
cat > "${ENV_FILE}" <<EOF
# =============================================================================
# Eulard Local Development Environment
# Generated by scripts/pull-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT — this file is in .gitignore
# =============================================================================

# --- Database (local docker-compose postgres) ---
DB_HOST=127.0.0.1
DB_PORT=5433
DB_NAME=eulard
DB_USER=eulard-app
DB_PASSWORD=${DB_PASSWORD:-localdev}
DB_SSL=false

# --- NextAuth ---
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
AUTH_TRUST_HOST=true

# --- Google OAuth ---
AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET}
AUTH_GOOGLE_ALLOWED_DOMAINS=kelihi.com

# --- Anthropic AI ---
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# --- Admin ---
ADMIN_EMAILS=chu@kelihi.com,alex@kelihi.com
EOF

echo "==> Written to ${ENV_FILE}"
echo ""
echo "NOTE: .env.local is gitignored. To use docker-compose, the app service"
echo "      reads this file via env_file. To run pnpm dev natively, Next.js"
echo "      auto-loads .env.local."
